import { RpcId } from '@lvce-editor/constants'

export const {
  ClipBoardProcess,
  ClipBoardWorker,
  ColorPickerWorker,
  CompletionWorker,
  DebugWorker,
  EditorWorker,
  EmbedsProcess,
  EmbedsWorker,
  ErrorWorker,
  ExtensionDetailWorker,
  ExtensionHostWorker,
  FileSystemProcess,
  FileSystemWorker,
  MainProcess,
  MarkdownWorker,
  OutputWorker,
  ProblemsWorker,
  RendererProcess,
  RendererWorker,
  SearchProcess,
  SearchProcessElectron,
  SharedProcess,
  SourceActionWorker,
  SourceControlWorker,
  SyntaxHighlightingWorker,
  TestWorker,
} = RpcId
